### ISSUE TITLE
Moving to `grunt-assemble-drafts`

### ISSUE THREAD

**Issue by doowb** [ghost-town/assemble-middleware-drafts#1]
I'll be moving the `grunt-assemble` version of this code to `grunt-assemble-drafts` and deprecating `assemble-middleware-drafts` on npm. If anyone has any issues/questions/comments, please leave them here so we may discuss.

**Comment by doowb** [comment]
@jonschlinkert just noticed that this was never compatible with `grunt-assemble`. Do you want to try to back port it to `grunt-assemble`? I'm not sure if it's worth the effort.

**Comment by jonschlinkert** [comment]
no, just deprecate I think. we can move it to ghost-town! lol

**Comment by doowb** [comment]
:+1:

**Comment by doowb** [comment]
Moving to ghost-town.
